services:
  postgres:
    container_name: postgres-container
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'cycleconnect'

    volumes:
      - cycleconnect-postgres:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    networks:
      - backend

  redis:
    container_name: redis-container
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - cycleconnect-redis:/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  cycleconnect-postgres:
  cycleconnect-redis:
